//! # Zero-Config Self-Healing API Scaffolder
//!
//! Bridges Vella's `ModelSchema` and `TypeScriptGenerator` with Tagisan's
//! Bun execution runtime. Automatically generates production-grade, strongly-typed
//! Bun.serve HTTP API servers from dynamic schemas, and automatically self-heals
//! when schema definitions evolve or drift.

use crate::bun::runtime::BunRuntime;
use crate::error::{Result, TagisanError};
use crate::tools::ToolHandler;
use async_trait::async_trait;
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use std::sync::Arc;
use tokio::sync::RwLock;
use tracing::{info, warn};

#[cfg(feature = "vella")]
use vella::{
    model::SchemaRegistry,
    types::TypeScriptGenerator,
};

/// Result of an automated self-healing audit
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SelfHealingReport {
    pub schema_name: String,
    pub detected_drift: bool,
    pub missing_fields: Vec<String>,
    pub outdated_fields: Vec<String>,
    pub healed: bool,
    pub updated_ts_code: String,
}

/// Dynamic API Scaffolder and Self-Healing Engine
#[derive(Clone)]
pub struct ApiScaffolderEngine {
    #[cfg(feature = "vella")]
    pub registry: Arc<RwLock<SchemaRegistry>>,
    pub runtime: Arc<BunRuntime>,
}

impl Default for ApiScaffolderEngine {
    fn default() -> Self {
        #[cfg(feature = "vella")]
        {
            Self {
                registry: Arc::new(RwLock::new(SchemaRegistry::default())),
                runtime: Arc::new(BunRuntime::new().unwrap_or_else(|_| BunRuntime::with_path("bun"))),
            }
        }
        #[cfg(not(feature = "vella"))]
        {
            Self {
                runtime: Arc::new(BunRuntime::new().unwrap_or_else(|_| BunRuntime::with_path("bun"))),
            }
        }
    }
}

impl ApiScaffolderEngine {
    pub fn new() -> Self {
        Self::default()
    }

    #[cfg(feature = "vella")]
    pub fn with_registry(registry: Arc<RwLock<SchemaRegistry>>) -> Self {
        Self {
            registry,
            runtime: Arc::new(BunRuntime::new().unwrap_or_else(|_| BunRuntime::with_path("bun"))),
        }
    }

    /// Generates a complete, self-contained Bun.serve TypeScript API server
    pub async fn generate_bun_api_server(
        &self,
        port: u16,
        custom_schemas: Option<Vec<Value>>,
    ) -> Result<String> {
        let mut interfaces = Vec::new();
        let mut model_names = Vec::new();
        let mut model_validation = Vec::new();

        #[cfg(feature = "vella")]
        {
            let reg = self.registry.read().await;
            for schema in reg.all() {
                let name = &schema.name;
                interfaces.push(TypeScriptGenerator::generate_model_interface(schema));
                model_names.push(name.clone());

                let required_fields: Vec<String> = schema
                    .fields
                    .iter()
                    .filter(|f| f.required && f.name != "id")
                    .map(|f| format!("'{}'", f.name))
                    .collect();

                model_validation.push(format!(
                    "  if (model === '{}') return [{}];",
                    name,
                    required_fields.join(", ")
                ));
            }
        }

        // Incorporate any ad-hoc JSON schemas passed in arguments
        if let Some(schemas) = custom_schemas {
            for s in schemas {
                if let Some(name) = s.get("name").and_then(|v| v.as_str()) {
                    model_names.push(name.to_string());
                    interfaces.push(format!(
                        "export interface {} {{\n  id: string;\n  [key: string]: any;\n}}",
                        name
                    ));
                    model_validation.push(format!("  if (model === '{}') return ['id'];", name));
                }
            }
        }

        if model_names.is_empty() {
            model_names.push("agent_executions".to_string());
            model_names.push("scada_telemetry".to_string());
            interfaces.push(
                r#"export interface agent_executions {
  id: string;
  agent_id: string;
  action: string;
  status: string;
}"#
                .to_string(),
            );
            interfaces.push(
                r#"export interface scada_telemetry {
  id: string;
  station_id: string;
  coil_address: number;
  reading: number;
}"#
                .to_string(),
            );
            model_validation.push("  if (model === 'agent_executions') return ['agent_id', 'action'];".to_string());
            model_validation.push("  if (model === 'scada_telemetry') return ['station_id', 'coil_address'];".to_string());
        }

        let code = format!(
            r#"// ============================================================================
// ⚡ Vella-Tagisan Sovereign Self-Healing API Server
// Auto-generated by VellaScaffolderTool on Bun.serve
// ============================================================================

import {{ serve }} from "bun";

// 1. Domain Type Definitions
{}

// In-memory data store for live models
const database: Record<string, any[]> = {{
{}
}};

function getRequiredFields(model: string): string[] {{
{}
  return [];
}}

export default {{
  port: {},
  async fetch(req: Request): Promise<Response> {{
    const url = new URL(req.url);
    const method = req.method;
    const path = url.pathname;

    // Health Check Endpoint
    if (path === "/health") {{
      return Response.json({{
        status: "nominal",
        server: "Vella-Tagisan Sovereign API",
        runtime: "bun " + Bun.version,
        timestamp: new Date().toISOString()
      }});
    }}

    // List Registered Schemas
    if (path === "/api/v1/schemas") {{
      return Response.json({{
        models: Object.keys(database),
        total_models: Object.keys(database).length
      }});
    }}

    // Dynamic CRUD Route Matching: /api/v1/:model or /api/v1/:model/:id
    const parts = path.split("/").filter(Boolean);
    if (parts.length >= 3 && parts[0] === "api" && parts[1] === "v1") {{
      const model = parts[2];
      const id = parts[3];

      if (!database[model]) {{
        return Response.json({{ error: `Model '${{model}}' not found` }}, {{ status: 404 }});
      }}

      // GET /api/v1/:model (List or Query)
      if (method === "GET" && !id) {{
        return Response.json({{ model, count: database[model].length, data: database[model] }});
      }}

      // GET /api/v1/:model/:id (Get Single)
      if (method === "GET" && id) {{
        const item = database[model].find((x: any) => String(x.id) === id);
        if (!item) return Response.json({{ error: `Item ${{id}} not found in ${{model}}` }}, {{ status: 404 }});
        return Response.json(item);
      }}

      // POST /api/v1/:model (Create with Schema Validation)
      if (method === "POST" && !id) {{
        try {{
          const body = await req.json();
          const required = getRequiredFields(model);
          for (const reqField of required) {{
            if (body[reqField] === undefined || body[reqField] === null) {{
              return Response.json({{ error: `Validation failed: missing required field '${{reqField}}'` }}, {{ status: 400 }});
            }}
          }}
          const newItem = {{ id: body.id || `rec_${{Date.now()}}_${{Math.random().toString(36).slice(2, 7)}}`, ...body }};
          database[model].push(newItem);
          return Response.json({{ status: "created", item: newItem }}, {{ status: 201 }});
        }} catch (e: any) {{
          return Response.json({{ error: `Invalid JSON payload: ${{e.message}}` }}, {{ status: 400 }});
        }}
      }}

      // DELETE /api/v1/:model/:id
      if (method === "DELETE" && id) {{
        const idx = database[model].findIndex((x: any) => String(x.id) === id);
        if (idx === -1) return Response.json({{ error: `Item ${{id}} not found` }}, {{ status: 404 }});
        const deleted = database[model].splice(idx, 1);
        return Response.json({{ status: "deleted", item: deleted[0] }});
      }}
    }}

    return Response.json({{ error: "Not Found", path }}, {{ status: 404 }});
  }}
}};
"#,
            interfaces.join("\n\n"),
            model_names
                .iter()
                .map(|m| format!("  '{}': [],", m))
                .collect::<Vec<_>>()
                .join("\n"),
            model_validation.join("\n"),
            port
        );

        info!(
            "🛠️ [Vella Scaffolder] Generated TypeScript Bun API server with {} models for port {}",
            model_names.len(),
            port
        );

        Ok(code)
    }

    /// Self-heals TypeScript server source when schemas have evolved
    pub async fn self_heal_server_code(
        &self,
        existing_ts_code: &str,
        target_schema_name: &str,
        expected_fields: &[String],
    ) -> Result<SelfHealingReport> {
        let mut missing_fields = Vec::new();

        for field in expected_fields {
            if !existing_ts_code.contains(field) {
                missing_fields.push(field.clone());
            }
        }

        let detected_drift = !missing_fields.is_empty();

        if detected_drift {
            warn!(
                "⚠️ [Vella Scaffolder] Schema drift detected in '{}'! Missing fields: {:?}",
                target_schema_name, missing_fields
            );

            // Re-generate updated clean server
            let updated_code = self.generate_bun_api_server(3000, None).await?;

            info!(
                "🩹 [Vella Scaffolder] Automatically healed API server for schema '{}'",
                target_schema_name
            );

            Ok(SelfHealingReport {
                schema_name: target_schema_name.to_string(),
                detected_drift: true,
                missing_fields,
                outdated_fields: Vec::new(),
                healed: true,
                updated_ts_code: updated_code,
            })
        } else {
            info!(
                "✅ [Vella Scaffolder] Schema '{}' is 100% in sync with TypeScript API code",
                target_schema_name
            );

            Ok(SelfHealingReport {
                schema_name: target_schema_name.to_string(),
                detected_drift: false,
                missing_fields: Vec::new(),
                outdated_fields: Vec::new(),
                healed: false,
                updated_ts_code: existing_ts_code.to_string(),
            })
        }
    }
}

// =========================================================================
// Tool Handler Implementation
// =========================================================================

/// Tool exposing Zero-Config Self-Healing API Scaffolder
#[derive(Clone)]
pub struct VellaScaffolderTool {
    pub scaffolder: ApiScaffolderEngine,
}

impl Default for VellaScaffolderTool {
    fn default() -> Self {
        Self::new(ApiScaffolderEngine::default())
    }
}

impl VellaScaffolderTool {
    pub fn new(scaffolder: ApiScaffolderEngine) -> Self {
        Self { scaffolder }
    }
}

#[async_trait]
impl ToolHandler for VellaScaffolderTool {
    fn name(&self) -> &'static str {
        "vella_api_scaffolder"
    }

    fn description(&self) -> &'static str {
        "Zero-Config Self-Healing API Scaffolder. Generates strongly-typed TypeScript Bun.serve API servers directly from Vella schemas, and automatically self-heals when schema definitions drift."
    }

    fn parameters_schema(&self) -> Value {
        json!({
            "type": "object",
            "properties": {
                "action": {
                    "type": "string",
                    "enum": ["generate_server", "self_heal", "validate_syntax"],
                    "description": "Scaffolder operation to perform"
                },
                "port": { "type": "integer", "default": 3000, "description": "Port for Bun.serve" },
                "custom_schemas": {
                    "type": "array",
                    "items": { "type": "object" },
                    "description": "Optional custom schema definitions"
                },
                "existing_code": { "type": "string", "description": "Existing TypeScript server code to audit and heal" },
                "schema_name": { "type": "string", "description": "Target model schema name" },
                "expected_fields": {
                    "type": "array",
                    "items": { "type": "string" },
                    "description": "Fields required by current schema version"
                }
            },
            "required": ["action"]
        })
    }

    async fn execute(&self, arguments: Value) -> Result<String> {
        let action = arguments
            .get("action")
            .and_then(|v| v.as_str())
            .ok_or_else(|| TagisanError::Execution("Missing 'action' parameter".to_string()))?;

        let res: Value = match action {
            "generate_server" => {
                let port = arguments.get("port").and_then(|v| v.as_u64()).unwrap_or(3000) as u16;
                let custom = arguments
                    .get("custom_schemas")
                    .and_then(|v| v.as_array())
                    .cloned();

                let code = self.scaffolder.generate_bun_api_server(port, custom).await?;

                json!({
                    "status": "success",
                    "action": "generate_server",
                    "port": port,
                    "generated_code_bytes": code.len(),
                    "typescript_code": code
                })
            }
            "self_heal" => {
                let existing = arguments
                    .get("existing_code")
                    .and_then(|v| v.as_str())
                    .unwrap_or("// outdated code");
                let schema_name = arguments
                    .get("schema_name")
                    .and_then(|v| v.as_str())
                    .unwrap_or("agent_executions");
                let expected: Vec<String> = arguments
                    .get("expected_fields")
                    .and_then(|v| v.as_array())
                    .map(|arr| {
                        arr.iter()
                            .filter_map(|x| x.as_str().map(|s| s.to_string()))
                            .collect()
                    })
                    .unwrap_or_else(|| vec!["agent_id".to_string(), "action".to_string()]);

                let report = self
                    .scaffolder
                    .self_heal_server_code(existing, schema_name, &expected)
                    .await?;

                json!({
                    "status": "success",
                    "action": "self_heal",
                    "report": report
                })
            }
            "validate_syntax" => {
                let code = arguments
                    .get("existing_code")
                    .and_then(|v| v.as_str())
                    .unwrap_or("console.log('API validated');");

                // Evaluate via Bun runtime
                let result = self
                    .scaffolder
                    .runtime
                    .eval(code, std::time::Duration::from_secs(5), None, None)
                    .await?;

                json!({
                    "status": "success",
                    "syntax_valid": result.is_success(),
                    "runtime_output": result.stdout
                })
            }
            _ => {
                return Err(TagisanError::Execution(format!(
                    "Unknown action '{}'. Valid actions: generate_server, self_heal, validate_syntax",
                    action
                )));
            }
        };

        serde_json::to_string_pretty(&res).map_err(|e| TagisanError::Execution(e.to_string()))
    }
}
