//! Erlang source code generator and binary External Term Format (ETF) term synthesizer for Gleam AST.
//!
//! Bridges typed Gleam modules directly to Erlang BEAM source and wires binary ETF terms
//! using Tagisan's native `src/otp/etf.rs` encoder/decoder.

use std::fmt::Write as _;
use thiserror::Error;

use crate::gleam::ast::*;
use crate::otp::etf::{EtfDecoder, EtfEncoder, EtfError, Term};

#[derive(Debug, Clone, PartialEq, Eq, Error)]
pub enum CodegenError {
    #[error("Failed to generate code: {0}")]
    GenerationFailed(String),
    #[error("ETF serialization error: {0}")]
    EtfError(String),
    #[error("Expression cannot be statically evaluated to ETF term: {0}")]
    StaticEvaluationFailed(String),
}

impl From<EtfError> for CodegenError {
    fn from(e: EtfError) -> Self {
        CodegenError::EtfError(e.to_string())
    }
}

// -----------------------------------------------------------------------------
// Erlang Source Code Generator
// -----------------------------------------------------------------------------

pub struct ErlangCodeGen {
    module: GleamModule,
}

impl ErlangCodeGen {
    pub fn new(module: GleamModule) -> Self {
        Self { module }
    }

    /// Compile Gleam module to complete Erlang source code (`.erl`)
    pub fn compile(&self) -> Result<String, CodegenError> {
        let mut out = String::with_capacity(2048);

        // Header
        let mod_atom = to_snake_case(&self.module.name);
        writeln!(&mut out, "%% -*- mode: erlang -*-").unwrap();
        writeln!(&mut out, "%% Generated by Tagisan Sovereign Gleam Compiler v0.2.0").unwrap();
        writeln!(&mut out, "-module({}).", mod_atom).unwrap();

        // Export list
        let exports: Vec<String> = self
            .module
            .functions
            .iter()
            .filter(|f| f.is_pub)
            .map(|f| format!("{}/{}", to_snake_case(&f.name), f.parameters.len()))
            .collect();

        if !exports.is_empty() {
            writeln!(&mut out, "-export([{}]).", exports.join(", ")).unwrap();
        }
        writeln!(&mut out).unwrap();

        // Functions
        for func in &self.module.functions {
            self.compile_function(func, &mut out)?;
            writeln!(&mut out).unwrap();
        }

        Ok(out)
    }

    fn compile_function(&self, func: &FunctionDefinition, out: &mut String) -> Result<(), CodegenError> {
        let fn_name = to_snake_case(&func.name);
        let params: Vec<String> = func
            .parameters
            .iter()
            .map(|p| to_erlang_var(&p.name))
            .collect();

        write!(out, "{}({}) ->\n", fn_name, params.join(", ")).unwrap();

        if func.body.is_empty() {
            writeln!(out, "    nil.").unwrap();
            return Ok(());
        }

        for (idx, stmt) in func.body.iter().enumerate() {
            let is_last = idx == func.body.len() - 1;
            let terminator = if is_last { "." } else { "," };
            let stmt_str = self.compile_statement(stmt, 1)?;
            writeln!(out, "    {}{}", stmt_str, terminator).unwrap();
        }

        Ok(())
    }

    fn compile_statement(&self, stmt: &Statement, indent: usize) -> Result<String, CodegenError> {
        match stmt {
            Statement::Let { pattern, value, .. } => {
                let pat_str = self.compile_pattern(pattern)?;
                let val_str = self.compile_expression(value, indent)?;
                Ok(format!("{} = {}", pat_str, val_str))
            }
            Statement::Expression(expr) => self.compile_expression(expr, indent),
            Statement::Use { patterns, call } => {
                let pat_str: Vec<String> = patterns
                    .iter()
                    .map(|p| self.compile_pattern(p))
                    .collect::<Result<_, _>>()?;
                let call_str = self.compile_expression(call, indent)?;
                Ok(format!("({})(fun({}) -> ... end)", call_str, pat_str.join(", ")))
            }
        }
    }

    fn compile_pattern(&self, pattern: &Pattern) -> Result<String, CodegenError> {
        match pattern {
            Pattern::Discard(name) => {
                if let Some(n) = name {
                    Ok(to_erlang_var(n))
                } else {
                    Ok("_".to_string())
                }
            }
            Pattern::Variable(name) => Ok(to_erlang_var(name)),
            Pattern::Literal(lit) => Ok(self.compile_literal(lit)),
            Pattern::Tuple(elements) => {
                let elems: Vec<String> = elements
                    .iter()
                    .map(|e| self.compile_pattern(e))
                    .collect::<Result<_, _>>()?;
                Ok(format!("{{{}}}", elems.join(", ")))
            }
            Pattern::List { elements, tail } => {
                let elems: Vec<String> = elements
                    .iter()
                    .map(|e| self.compile_pattern(e))
                    .collect::<Result<_, _>>()?;
                if let Some(t) = tail {
                    let tail_str = self.compile_pattern(t)?;
                    Ok(format!("[{} | {}]", elems.join(", "), tail_str))
                } else {
                    Ok(format!("[{}]", elems.join(", ")))
                }
            }
            Pattern::Constructor { name, args, .. } => {
                let atom_tag = to_snake_case(name);
                if args.is_empty() {
                    Ok(atom_tag)
                } else {
                    let mut parts = vec![atom_tag];
                    for arg in args {
                        parts.push(self.compile_pattern(&arg.pattern)?);
                    }
                    Ok(format!("{{{}}}", parts.join(", ")))
                }
            }
            Pattern::Or(p1, p2) => {
                let s1 = self.compile_pattern(p1)?;
                let s2 = self.compile_pattern(p2)?;
                Ok(format!("{} ; {}", s1, s2))
            }
        }
    }

    fn compile_expression(&self, expr: &Expression, indent: usize) -> Result<String, CodegenError> {
        match expr {
            Expression::Literal(lit) => Ok(self.compile_literal(lit)),
            Expression::Variable(name) => {
                // If it's a known function or starts with lowercase, check if variable or atom
                Ok(to_erlang_var(name))
            }
            Expression::BinOp { op, left, right } => {
                let l = self.compile_expression(left, indent)?;
                let r = self.compile_expression(right, indent)?;

                match op {
                    BinOp::Add | BinOp::AddFloat => Ok(format!("({} + {})", l, r)),
                    BinOp::Sub | BinOp::SubFloat => Ok(format!("({} - {})", l, r)),
                    BinOp::Mul | BinOp::MulFloat => Ok(format!("({} * {})", l, r)),
                    BinOp::Div => Ok(format!("({} div {})", l, r)),
                    BinOp::DivFloat => Ok(format!("({} / {})", l, r)),
                    BinOp::Mod => Ok(format!("({} rem {})", l, r)),
                    BinOp::Eq => Ok(format!("({} =:= {})", l, r)),
                    BinOp::NotEq => Ok(format!("({} =/= {})", l, r)),
                    BinOp::Lt => Ok(format!("({} < {})", l, r)),
                    BinOp::LtEq => Ok(format!("({} =< {})", l, r)),
                    BinOp::Gt => Ok(format!("({} > {})", l, r)),
                    BinOp::GtEq => Ok(format!("({} >= {})", l, r)),
                    BinOp::And => Ok(format!("({} andalso {})", l, r)),
                    BinOp::Or => Ok(format!("({} orelse {})", l, r)),
                    BinOp::Concat => Ok(format!("<<({})/binary, ({})/binary>>", l, r)),
                    BinOp::Pipe => {
                        // Desugar pipe: `l |> f(r)` -> `f(l, r)`
                        match right.as_ref() {
                            Expression::FunctionCall { function, arguments } => {
                                let func_str = self.compile_expression(function, indent)?;
                                let mut arg_strs = vec![l];
                                for a in arguments {
                                    arg_strs.push(self.compile_expression(&a.value, indent)?);
                                }
                                Ok(format!("{}({})", func_str, arg_strs.join(", ")))
                            }
                            Expression::Variable(f) => {
                                Ok(format!("{}({})", to_snake_case(f), l))
                            }
                            _ => Ok(format!("{}({})", r, l)),
                        }
                    }
                }
            }
            Expression::FunctionCall { function, arguments } => {
                let func_str = match function.as_ref() {
                    Expression::Variable(v) => to_snake_case(v),
                    Expression::FieldAccess { record, field } => {
                        let rec = self.compile_expression(record, indent)?;
                        format!("{}:{}", to_snake_case(&rec), to_snake_case(field))
                    }
                    _ => self.compile_expression(function, indent)?,
                };

                let mut arg_strs = Vec::new();
                for arg in arguments {
                    arg_strs.push(self.compile_expression(&arg.value, indent)?);
                }
                Ok(format!("{}({})", func_str, arg_strs.join(", ")))
            }
            Expression::RecordCreation { constructor, fields, .. } => {
                let atom_tag = to_snake_case(constructor);
                if fields.is_empty() {
                    Ok(atom_tag)
                } else {
                    let mut parts = vec![atom_tag];
                    for (_, val) in fields {
                        parts.push(self.compile_expression(val, indent)?);
                    }
                    Ok(format!("{{{}}}", parts.join(", ")))
                }
            }
            Expression::FieldAccess { record, field } => {
                let rec_str = self.compile_expression(record, indent)?;
                Ok(format!("maps:get({}, {})", to_snake_case(field), rec_str))
            }
            Expression::TupleAccess { tuple, index } => {
                let tup_str = self.compile_expression(tuple, indent)?;
                Ok(format!("element({}, {})", index + 1, tup_str))
            }
            Expression::Case { subject, clauses } => {
                let sub_str = self.compile_expression(subject, indent)?;
                let mut out = format!("case {} of\n", sub_str);
                let ind = "    ".repeat(indent + 1);

                for (idx, clause) in clauses.iter().enumerate() {
                    let is_last = idx == clauses.len() - 1;
                    let terminator = if is_last { "" } else { ";" };
                    let pat_str = self.compile_pattern(&clause.pattern)?;
                    let guard_str = if let Some(ref g) = clause.guard {
                        format!(" when {}", self.compile_expression(g, indent + 1)?)
                    } else {
                        String::new()
                    };
                    let body_str = self.compile_expression(&clause.body, indent + 2)?;
                    out.push_str(&format!("{}{}{} ->\n{}    {}{}\n", ind, pat_str, guard_str, ind, body_str, terminator));
                }

                out.push_str(&format!("{}end", "    ".repeat(indent)));
                Ok(out)
            }
            Expression::Block(stmts) => {
                let mut lines = Vec::new();
                for (idx, stmt) in stmts.iter().enumerate() {
                    let is_last = idx == stmts.len() - 1;
                    let terminator = if is_last { "" } else { "," };
                    let s = self.compile_statement(stmt, indent)?;
                    lines.push(format!("{}{}", s, terminator));
                }
                Ok(lines.join("\n"))
            }
            Expression::Tuple(elements) => {
                let elems: Vec<String> = elements
                    .iter()
                    .map(|e| self.compile_expression(e, indent))
                    .collect::<Result<_, _>>()?;
                Ok(format!("{{{}}}", elems.join(", ")))
            }
            Expression::List(elements) => {
                let elems: Vec<String> = elements
                    .iter()
                    .map(|e| self.compile_expression(e, indent))
                    .collect::<Result<_, _>>()?;
                Ok(format!("[{}]", elems.join(", ")))
            }
            Expression::AnonymousFunction { parameters, body, .. } => {
                let params: Vec<String> = parameters.iter().map(|p| to_erlang_var(&p.name)).collect();
                let mut body_lines = Vec::new();
                for (idx, stmt) in body.iter().enumerate() {
                    let is_last = idx == body.len() - 1;
                    let terminator = if is_last { "" } else { "," };
                    let s = self.compile_statement(stmt, indent + 1)?;
                    body_lines.push(format!("{}{}", s, terminator));
                }
                Ok(format!("fun({}) ->\n    {}\nend", params.join(", "), body_lines.join("\n    ")))
            }
            Expression::Panic(reason) => {
                if let Some(r) = reason {
                    Ok(format!("erlang:error({:?})", r))
                } else {
                    Ok("erlang:error(panic)".to_string())
                }
            }
            Expression::Todo(reason) => {
                if let Some(r) = reason {
                    Ok(format!("erlang:error({{:todo, {:?}}})", r))
                } else {
                    Ok("erlang:error(todo)".to_string())
                }
            }
        }
    }

    fn compile_literal(&self, lit: &Literal) -> String {
        match lit {
            Literal::Int(i) => i.to_string(),
            Literal::Float(f) => format!("{:?}", f),
            Literal::String(s) => format!("<<{:?}>>", s),
            Literal::Bool(b) => if *b { "true".to_string() } else { "false".to_string() },
            Literal::Nil => "nil".to_string(),
        }
    }
}

// -----------------------------------------------------------------------------
// Binary ETF Term Synthesizer
// -----------------------------------------------------------------------------

pub struct EtfSynthesizer;

impl EtfSynthesizer {
    /// Synthesize a binary ETF representation of a custom Gleam constructor and its arguments
    pub fn synthesize_constructor(constructor: &str, args: &[Term]) -> Term {
        let tag = Term::atom(to_snake_case(constructor));
        if args.is_empty() {
            tag
        } else {
            let mut tuple_elements = vec![tag];
            tuple_elements.extend_from_slice(args);
            Term::tuple(tuple_elements)
        }
    }

    /// Convert a statically evaluable Gleam expression into an ETF Term
    pub fn term_from_expression(expr: &Expression) -> Result<Term, CodegenError> {
        match expr {
            Expression::Literal(lit) => Ok(match lit {
                Literal::Int(i) => Term::int(*i),
                Literal::Float(f) => Term::float(*f),
                Literal::String(s) => Term::binary(s.as_bytes().to_vec()),
                Literal::Bool(b) => Term::boolean(*b),
                Literal::Nil => Term::atom("nil"),
            }),
            Expression::Tuple(elements) => {
                let terms = elements
                    .iter()
                    .map(Self::term_from_expression)
                    .collect::<Result<Vec<_>, _>>()?;
                Ok(Term::tuple(terms))
            }
            Expression::List(elements) => {
                let terms = elements
                    .iter()
                    .map(Self::term_from_expression)
                    .collect::<Result<Vec<_>, _>>()?;
                Ok(Term::list(terms))
            }
            Expression::RecordCreation { constructor, fields, .. } => {
                let args = fields
                    .iter()
                    .map(|(_, e)| Self::term_from_expression(e))
                    .collect::<Result<Vec<_>, _>>()?;
                Ok(Self::synthesize_constructor(constructor, &args))
            }
            _ => Err(CodegenError::StaticEvaluationFailed(format!("{:?}", expr))),
        }
    }

    /// Encode a Term into a binary ETF packet (prefixed with tag 131)
    pub fn encode(term: &Term) -> Vec<u8> {
        EtfEncoder::encode(term)
    }

    /// Decode a binary ETF packet back into a Term
    pub fn decode(bytes: &[u8]) -> Result<Term, CodegenError> {
        EtfDecoder::decode(bytes).map_err(CodegenError::from)
    }
}

// -----------------------------------------------------------------------------
// Naming Utilities
// -----------------------------------------------------------------------------

pub fn to_snake_case(s: &str) -> String {
    let mut result = String::with_capacity(s.len() + 4);
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() {
            if i > 0 {
                result.push('_');
            }
            result.extend(c.to_lowercase());
        } else {
            result.push(c);
        }
    }
    result
}

pub fn to_erlang_var(s: &str) -> String {
    if s == "_" {
        return "_".to_string();
    }
    let mut chars = s.chars();
    match chars.next() {
        None => String::new(),
        Some(first) => {
            let mut result = String::new();
            result.extend(first.to_uppercase());
            result.extend(chars);
            result
        }
    }
}
