#!/usr/bin/env bun
/**
 * Deterministically (re)build `rules/_index.md` from `rules/*.md`.
 *
 * Usage:
 *   bun scripts/build-rules-index.ts
 */

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const skillRoot = path.resolve(__dirname, "..");
const rulesDir = path.join(skillRoot, "rules");
const outPath = path.join(rulesDir, "_index.md");

type RuleEntry = Readonly<{
  id: string;
  fileName: string;
  title: string;
  group: string;
}>;

function extractTitle(markdown: string): string {
  // Prefer YAML frontmatter `title: ...` if present.
  const fm = markdown.match(/^---\n([\s\S]*?)\n---\n/m);
  if (fm) {
    const titleLine = fm[1]
      .split("\n")
      .map((l) => l.trim())
      .find((l) => l.startsWith("title:"));
    if (titleLine) {
      const raw = titleLine.replace(/^title:\s*/, "").trim();
      return raw.replace(/^["']/, "").replace(/["']$/, "");
    }
  }

  const h1 = markdown.match(/^#\s+(.+)\n/m);
  if (h1) return h1[1].trim();
  return "Untitled";
}

function groupForRuleId(ruleId: string): string {
  const idx = ruleId.indexOf("-");
  return idx === -1 ? "other" : ruleId.slice(0, idx);
}

const files = readdirSync(rulesDir)
  .filter((f) => f.endsWith(".md"))
  .filter((f) => f !== "_index.md")
  .sort((a, b) => a.localeCompare(b));

const entries: RuleEntry[] = files.map((fileName) => {
  const id = fileName.replace(/\.md$/, "");
  const group = groupForRuleId(id);
  const content = readFileSync(path.join(rulesDir, fileName), "utf8");
  const title = extractTitle(content);
  return { id, fileName, title, group };
});

const groups = Array.from(new Set(entries.map((e) => e.group))).sort((a, b) =>
  a.localeCompare(b),
);

const lines: string[] = [];
lines.push("# Zod v4 Rules Index");
lines.push("");
lines.push("This file is generated by `scripts/build-rules-index.ts`.");
lines.push("");
lines.push("## Groups");
lines.push("");
for (const g of groups) {
  lines.push(`- ${g}`);
}
lines.push("");

for (const g of groups) {
  lines.push(`## ${g}`);
  lines.push("");
  const groupEntries = entries
    .filter((e) => e.group === g)
    .sort((a, b) => a.id.localeCompare(b.id));
  for (const e of groupEntries) {
    lines.push(`- \`${e.id}\`: [${e.title}](./${e.fileName})`);
  }
  lines.push("");
}

writeFileSync(outPath, `${lines.join("\n")}\n`, "utf8");
console.log(`Wrote ${path.relative(skillRoot, outPath)} (${entries.length} rules)`);
