use crate::engine::EngineContext;
use crate::error::{Result, TagisanError};
use crate::strategies::{CollaborationStrategy, IntermediateStep, StrategyInput, StrategyOutput};
use crate::types::{CompletionRequest, Message, TokenUsage};
use async_trait::async_trait;
use std::time::Instant;

/// Mixture-of-Agents (MoA) Collaboration Strategy
pub struct MixtureOfAgentsStrategy {
    /// List of (provider_id, model_name) for Layer 1 proposers
    pub proposers: Vec<(String, String)>,
    /// (provider_id, model_name) for final aggregator / synthesizer
    pub aggregator: (String, String),
}

impl MixtureOfAgentsStrategy {
    pub fn new(proposers: Vec<(String, String)>, aggregator: (String, String)) -> Self {
        Self {
            proposers,
            aggregator,
        }
    }
}

#[async_trait]
impl CollaborationStrategy for MixtureOfAgentsStrategy {
    fn name(&self) -> &'static str {
        "Mixture-of-Agents (MoA)"
    }

    async fn execute(&self, input: StrategyInput, ctx: &EngineContext) -> Result<StrategyOutput> {
        if ctx.cancellation_token.is_cancelled() {
            return Err(TagisanError::Cancelled);
        }

        let start_time = Instant::now();
        let mut intermediate_steps = Vec::new();
        let mut total_usage = TokenUsage::default();

        // 1. Parallel Proposer Queries
        let mut proposer_futures = Vec::new();
        for (idx, (provider_id, model_name)) in self.proposers.iter().enumerate() {
            let provider = ctx.get_provider(provider_id)?;
            let provider_id = provider_id.clone();
            let model_name = model_name.clone();
            let prompt = input.prompt.clone();
            let sys = input.system_instruction.clone();
            let cancel_token = ctx.cancellation_token.clone();

            proposer_futures.push(async move {
                let req = CompletionRequest {
                    model: model_name.clone(),
                    messages: vec![Message::user(prompt)],
                    temperature: Some(0.7),
                    max_tokens: Some(3000),
                    stream: false,
                    system_prompt: sys,
                    tools: Vec::new(),
                    tool_choice: None,
                    cancellation_token: Some(cancel_token),
                };
                let resp = provider.complete(req).await;
                (idx, provider_id, model_name, resp)
            });
        }

        let proposer_results = futures::future::join_all(proposer_futures).await;

        if ctx.cancellation_token.is_cancelled() {
            return Err(TagisanError::Cancelled);
        }

        let mut candidate_drafts = Vec::new();

        for (idx, provider_id, model_name, comp_res) in proposer_results {
            match comp_res {
                Ok(resp) => {
                    let _cost = ctx.budget_tracker.record(
                        &model_name,
                        resp.usage.prompt_tokens,
                        resp.usage.completion_tokens,
                    )?;

                    total_usage.prompt_tokens += resp.usage.prompt_tokens;
                    total_usage.completion_tokens += resp.usage.completion_tokens;

                    let text = resp.message.extract_text();
                    candidate_drafts.push(format!(
                        "--- Candidate Proposal {} (Generated by {} / {}) ---\n{}",
                        idx + 1,
                        provider_id,
                        model_name,
                        text
                    ));

                    intermediate_steps.push(IntermediateStep {
                        step_name: format!("Proposer #{}", idx + 1),
                        provider: provider_id,
                        model: model_name,
                        message: resp.message,
                        latency: resp.latency,
                    });
                }
                Err(e) => {
                    if matches!(e, TagisanError::Cancelled) {
                        return Err(TagisanError::Cancelled);
                    }
                    tracing::warn!("Proposer {} ({}) failed: {:?}", provider_id, model_name, e);
                }
            }
        }

        if candidate_drafts.is_empty() {
            return Err(TagisanError::Execution(
                "All MoA proposer models failed to return candidate responses.".into(),
            ));
        }

        if ctx.cancellation_token.is_cancelled() {
            return Err(TagisanError::Cancelled);
        }

        // 2. Synthesize with Master Aggregator
        let (agg_provider_id, agg_model_name) = &self.aggregator;
        let agg_provider = ctx.get_provider(agg_provider_id)?;

        let aggregator_prompt = format!(
            "You are the Lead Master Synthesizer in a Mixture-of-Agents architecture.\n\n\
            User Prompt:\n\"{}\"\n\n\
            Below are candidate proposals independently generated by peer expert AI models:\n\n\
            {}\n\n\
            TASK:\n\
            1. Analyze, critique, and cross-verify each candidate proposal.\n\
            2. Combine the best insights, fix all bugs/errors, and produce the definitive, highest-quality, comprehensive final response.",
            input.prompt,
            candidate_drafts.join("\n\n")
        );

        let agg_req = CompletionRequest {
            model: agg_model_name.clone(),
            messages: vec![Message::user(aggregator_prompt)],
            temperature: Some(0.3),
            max_tokens: Some(4096),
            stream: false,
            system_prompt: input.system_instruction.clone(),
            tools: Vec::new(),
            tool_choice: None,
            cancellation_token: Some(ctx.cancellation_token.clone()),
        };

        let agg_resp = agg_provider.complete(agg_req).await?;

        ctx.budget_tracker.record(
            agg_model_name,
            agg_resp.usage.prompt_tokens,
            agg_resp.usage.completion_tokens,
        )?;

        total_usage.prompt_tokens += agg_resp.usage.prompt_tokens;
        total_usage.completion_tokens += agg_resp.usage.completion_tokens;

        let final_text = agg_resp.message.extract_text();

        intermediate_steps.push(IntermediateStep {
            step_name: "Master Aggregator Synthesis".to_string(),
            provider: agg_provider_id.clone(),
            model: agg_model_name.clone(),
            message: agg_resp.message,
            latency: agg_resp.latency,
        });

        Ok(StrategyOutput {
            strategy_name: self.name(),
            final_answer: final_text,
            intermediate_steps,
            total_usage,
            total_cost_usd: ctx.budget_tracker.current_spent_usd(),
            total_latency: start_time.elapsed(),
        })
    }
}
