-- File: output/sql/{service}-schema.sql
-- {{service_name}} Microservice Database Schema
-- Generated by skills-microservices-designer
-- Derived from: spec.md, plan.md, Neo4j graph evidence (class business rules)
-- Evidence Sources: {{evidence_files}}

-- ============================================================================
-- SERVICE OWNERSHIP
-- This service has EXCLUSIVE WRITE ACCESS to owned tables.
-- Other services must access this data through APIs only.
-- No cross-microservice foreign keys are permitted.
-- Owned Tables : {{owned_tables}}
-- Read-Only    : {{readonly_tables}}
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS {{schema_name}};
SET search_path TO {{schema_name}};

-- ============================================================================
-- OWNED TABLES (Full Ownership)
-- Derived from: OWNS_DATA relationships in Neo4j / CSV "Database Tables" column
-- ============================================================================

-- Table: {{table_name}}
-- Purpose: {{purpose}}
-- Evidence: {{evidence_source}}
-- Business rules (from graphEvidence.classRules):
--   {{#business_rules}}
--   - {{rule}}
--   {{/business_rules}}
CREATE TABLE {{table_name}} (
    -- Primary key
    id               BIGSERIAL NOT NULL,

    -- Business columns (derived from plan.md data-model.md + graph Column nodes)
    -- {{column_name}} {{data_type}} {{constraints}}, -- {{comment}}

    -- Mandatory audit columns (NFR)
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by       VARCHAR(100) NOT NULL,
    updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by       VARCHAR(100) NOT NULL,

    -- Constraints
    CONSTRAINT pk_{{table_name}} PRIMARY KEY (id)
    -- CONSTRAINT uk_{{table_name}}_{{name}} UNIQUE ({{columns}})
    -- CONSTRAINT chk_{{table_name}}_{{name}} CHECK ({{condition}})  -- from businessRules
);

-- Indexes for performance
-- CREATE INDEX idx_{{table_name}}_{{col}} ON {{table_name}}({{col}});

-- Table comments
COMMENT ON TABLE {{table_name}} IS '{{description}}';
-- COMMENT ON COLUMN {{table_name}}.{{col}} IS '{{comment}}';

-- ============================================================================
-- FOREIGN KEY CONSTRAINTS (within this service's schema only)
-- No cross-microservice FKs allowed
-- ============================================================================
-- ALTER TABLE {{table_name}}
--     ADD CONSTRAINT fk_{{table_name}}_{{name}}
--     FOREIGN KEY ({{column}}) REFERENCES {{ref_table}}({{ref_column}})
--     ON DELETE {{action}};

-- ============================================================================
-- READ-ONLY VIEWS (data owned by other services — cached locally)
-- ============================================================================
-- CREATE VIEW {{view_name}} AS
-- SELECT {{columns}} FROM {{cache_table}};
-- COMMENT ON VIEW {{view_name}} IS 'Read-only cache of {{source_service}} data';

-- ============================================================================
-- MANDATORY: AUDIT TRAIL (NFR)
-- Captures INSERT / UPDATE / DELETE for all owned tables
-- Retention: 7 years
-- ============================================================================

CREATE TABLE {{schema_name}}_audit_log (
    audit_id       BIGSERIAL    PRIMARY KEY,
    table_name     VARCHAR(100) NOT NULL,
    record_id      VARCHAR(100) NOT NULL,
    operation      VARCHAR(20)  NOT NULL,
    old_values     JSONB,
    new_values     JSONB,
    correlation_id UUID,
    performed_by   VARCHAR(100) NOT NULL,
    performed_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_audit_operation CHECK (operation IN ('INSERT', 'UPDATE', 'DELETE'))
);

CREATE INDEX idx_{{schema_name}}_audit_table       ON {{schema_name}}_audit_log(table_name);
CREATE INDEX idx_{{schema_name}}_audit_record      ON {{schema_name}}_audit_log(record_id);
CREATE INDEX idx_{{schema_name}}_audit_correlation ON {{schema_name}}_audit_log(correlation_id);
CREATE INDEX idx_{{schema_name}}_audit_timestamp   ON {{schema_name}}_audit_log(performed_at);

COMMENT ON TABLE {{schema_name}}_audit_log IS 'Audit trail for all owned tables (NFR)';

-- ============================================================================
-- MANDATORY: OUTBOX TABLE (Saga / Event-Driven Architecture NFR)
-- Polling interval: 5 s  |  Retry: exponential backoff, max 3 attempts
-- ============================================================================

CREATE TABLE {{schema_name}}_outbox (
    outbox_id      UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    aggregate_type VARCHAR(100) NOT NULL,
    aggregate_id   VARCHAR(100) NOT NULL,
    event_type     VARCHAR(100) NOT NULL,
    payload        JSONB        NOT NULL,
    correlation_id UUID         NOT NULL,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at   TIMESTAMP,
    status         VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    retry_count    INTEGER      NOT NULL DEFAULT 0,
    error_message  TEXT,

    CONSTRAINT chk_outbox_status CHECK (status IN ('PENDING', 'PROCESSED', 'FAILED'))
);

CREATE INDEX idx_{{schema_name}}_outbox_pending    ON {{schema_name}}_outbox(status) WHERE status = 'PENDING';
CREATE INDEX idx_{{schema_name}}_outbox_created    ON {{schema_name}}_outbox(created_at);
CREATE INDEX idx_{{schema_name}}_outbox_correlation ON {{schema_name}}_outbox(correlation_id);

COMMENT ON TABLE {{schema_name}}_outbox IS 'Transactional outbox for reliable event publishing (NFR)';

-- ============================================================================
-- TRIGGERS
-- ============================================================================

-- Auto-update updated_at on every UPDATE
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- CREATE TRIGGER trg_{{table_name}}_updated_at
--     BEFORE UPDATE ON {{table_name}}
--     FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Audit trigger
CREATE OR REPLACE FUNCTION {{schema_name}}_audit_trigger_fn()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        INSERT INTO {{schema_name}}_audit_log
            (table_name, record_id, operation, new_values, performed_by)
        VALUES
            (TG_TABLE_NAME, NEW.id::TEXT, 'INSERT', row_to_json(NEW), current_user);
    ELSIF TG_OP = 'UPDATE' THEN
        INSERT INTO {{schema_name}}_audit_log
            (table_name, record_id, operation, old_values, new_values, performed_by)
        VALUES
            (TG_TABLE_NAME, NEW.id::TEXT, 'UPDATE', row_to_json(OLD), row_to_json(NEW), current_user);
    ELSIF TG_OP = 'DELETE' THEN
        INSERT INTO {{schema_name}}_audit_log
            (table_name, record_id, operation, old_values, performed_by)
        VALUES
            (TG_TABLE_NAME, OLD.id::TEXT, 'DELETE', row_to_json(OLD), current_user);
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- CREATE TRIGGER trg_{{table_name}}_audit
--     AFTER INSERT OR UPDATE OR DELETE ON {{table_name}}
--     FOR EACH ROW EXECUTE FUNCTION {{schema_name}}_audit_trigger_fn();

-- ============================================================================
-- MIGRATION NOTES
-- 1. Create schema in new database
-- 2. Migrate owned tables from monolith
-- 3. Set up replication for read-only data
-- 4. Update application connection strings
-- 5. Verify data integrity
-- 6. Cut over traffic
--
-- Rollback:
-- 1. Revert connection strings
-- 2. Sync any new data back to monolith
-- 3. Drop microservice schema
-- ============================================================================

-- ============================================================================
-- EVIDENCE TRACEABILITY
-- {{#evidence_sources}}
-- - {{file}}: {{description}}
-- {{/evidence_sources}}
-- ============================================================================

-- ============================================================================
-- OPEN QUESTIONS (unclear table ownership — document and resolve before cutover)
-- {{#open_questions}}
-- Q: {{question}}
--    Context: {{context}}
--    Impact : {{impact}}
-- {{/open_questions}}
-- ============================================================================
