use std::collections::HashMap;
use std::sync::RwLock;
use serde::{Deserialize, Serialize};
use crate::swarm::harmony::types::RoleArtifact;

/// Thread-safe, append-only blackboard shared across all roles in the pipeline.
#[derive(Debug, Default, Serialize, Deserialize)]
pub struct SwarmBlackboard {
    pub user_objective: String,
    artifacts: RwLock<Vec<RoleArtifact>>,
    metadata: RwLock<HashMap<String, String>>,
}

impl SwarmBlackboard {
    /// Create a new blackboard for a given user objective.
    pub fn new(objective: impl Into<String>) -> Self {
        Self {
            user_objective: objective.into(),
            artifacts: RwLock::new(Vec::new()),
            metadata: RwLock::new(HashMap::new()),
        }
    }

    /// Append an immutable artifact generated by a role stage.
    pub fn append_artifact(&self, artifact: RoleArtifact) {
        let mut list = self.artifacts.write().expect("Blackboard artifacts lock poisoned");
        list.push(artifact);
    }

    /// Retrieve all artifacts generated so far in chronological order.
    pub fn get_artifacts(&self) -> Vec<RoleArtifact> {
        let list = self.artifacts.read().expect("Blackboard artifacts lock poisoned");
        list.clone()
    }

    /// Get the specific artifact produced by a role ID (e.g. "architect", "implementer").
    pub fn get_artifact(&self, role_id: &str) -> Option<RoleArtifact> {
        let list = self.artifacts.read().expect("Blackboard artifacts lock poisoned");
        list.iter().find(|a| a.role_id == role_id).cloned()
    }

    /// Get the latest code snippet matching the requested language across all artifacts.
    pub fn get_latest_code_by_language(&self, lang: &str) -> Option<String> {
        let list = self.artifacts.read().expect("Blackboard artifacts lock poisoned");
        for artifact in list.iter().rev() {
            for block in &artifact.code_blocks {
                if block.language.eq_ignore_ascii_case(lang) {
                    return Some(block.code.clone());
                }
            }
        }
        None
    }

    /// Assembles all stages into a unified project code bundle with clear delimiters.
    pub fn assemble_complete_project(&self) -> String {
        let list = self.artifacts.read().expect("Blackboard artifacts lock poisoned");
        let mut buffer = String::new();

        buffer.push_str(&format!(
            "// =========================================================================\n\
             // PROJECT OBJECTIVE: {}\n\
             // Generated via Tagisan Structured Role-Based Harmony Swarm\n\
             // =========================================================================\n\n",
            self.user_objective
        ));

        for artifact in list.iter() {
            buffer.push_str(&format!(
                "// -------------------------------------------------------------------------\n\
                 // STAGE: {} - {} [{}: {}] (Latency: {:.2}s, Tokens: {})\n\
                 // -------------------------------------------------------------------------\n",
                artifact.role_id.to_uppercase(),
                artifact.role_title,
                artifact.provider,
                artifact.model,
                artifact.latency_secs,
                artifact.tokens_used
            ));

            if artifact.code_blocks.is_empty() {
                // If no code block, include clean raw output
                buffer.push_str(&artifact.raw_output);
                buffer.push_str("\n\n");
            } else {
                for block in &artifact.code_blocks {
                    buffer.push_str(&block.code);
                    buffer.push_str("\n\n");
                }
            }
        }

        buffer
    }

    /// Set an arbitrary metadata key-value pair.
    pub fn set_metadata(&self, key: impl Into<String>, value: impl Into<String>) {
        let mut map = self.metadata.write().expect("Blackboard metadata lock poisoned");
        map.insert(key.into(), value.into());
    }

    /// Retrieve a metadata value by key.
    pub fn get_metadata(&self, key: &str) -> Option<String> {
        let map = self.metadata.read().expect("Blackboard metadata lock poisoned");
        map.get(key).cloned()
    }

    /// Number of artifacts committed to the blackboard.
    pub fn len(&self) -> usize {
        let list = self.artifacts.read().expect("Blackboard artifacts lock poisoned");
        list.len()
    }

    /// Checks if the blackboard is empty.
    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }
}
